seed: 42

dataset:
  root: /home/cgv841/datasets/SYSU-MM01
  image_size: [224, 224]
  use_val: true

model:
  type: lastvit
  backbone_name: vit_base_patch16_224
  pretrained_path: /home/cgv841/.cache/torch/checkpoints/jx_vit_base_p16_224-80ecf9dd.pth
  drop_path_rate: 0.1
  topk: 1

loss:
  id_weight: 1.0
  triplet_weight: 1.0
  triplet_margin: 0.3

train:
  epochs: 8
  steps_per_epoch: 80
  num_ids: 8
  num_instances: 2
  num_workers: 8
  lr: 0.0003
  min_lr: 0.000001
  weight_decay: 0.05
  amp: true
  clip_grad_norm: 1.0
  eval_trials: 2

eval:
  batch_size: 128
  num_workers: 8
  num_trials: 10
