seed: 42

dataset:
  name: sysumm01
  root: /home/cgv841/datasets/SYSU-MM01
  image_size: [288, 144]
  use_val: false
  train_modality: both
  train_augment: strong_reid

model:
  type: partial_shared_dual_stream
  backbone_name: vit_base_patch16_224
  pretrained_path: /home/cgv841/ybj/pretrained/ViT_190k.pth
  drop_path_rate: 0.1
  image_size: [288, 144]
  split_block: 4
  patch_embed:
    anchor_branch: 0
    branches:
      - patch_size: [16, 16]
        stride: [12, 12]
      - patch_size: [16, 8]
        stride: [12, 6]

loss:
  id_weight: 1.0
  triplet_weight: 0.0
  triplet_margin: 0.3
  cross_batch_memory_size: 0
  reset_memory_each_epoch: true
  cross_modal_metric:
    enabled: true
    start_epoch: 1
    triplet:
      enabled: true
      weight: 1.0
      margin: 0.3

train:
  init_checkpoint: /home/cgv841/ybj/TVI-LFM/logs/external_rgb_ir/vcm_llcm_balanced_partial_shared_split4_ep40/checkpoints/last.pth
  init_partial_classifier: false
  epochs: 20
  steps_per_epoch: 400
  num_ids: 6
  num_instances: 4
  rgb_instances: 4
  ir_instances: 4
  num_workers: 8
  freeze_backbone_epochs: 0
  lr: 0.00001
  min_lr: 0.000001
  scheduler: warmup_cosine
  warmup_epochs: 2
  warmup_init_lr: 0.000001
  weight_decay: 0.0005
  amp: true
  clip_grad_norm: 1.0
  eval_trials: 2
  output_dir: /home/cgv841/ybj/TVI-LFM/logs/sysu_external_pretrain/vcm_llcm_balanced_partial_shared_finetune_ep20

eval:
  dataset_root: /home/cgv841/datasets/SYSU-MM01
  batch_size: 128
  num_workers: 8
  num_trials: 10
  selection_split: val
  final_split: test
  primary_mode: all
  extra_modes: [indoor]
  protocol: cross_modality
